# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: INHER
full_title: Institute of Natural History Education and Research
email: inher.pune@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Institute of Natural History Education and Research promotes scientific knowledge in natural history through research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://inher.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  
youtube_username: inherpune
facebook_username: INHERPUNE

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-paginate
